travis:
  secure:
    BINSTAR_TOKEN: jtfQESGchCwQjioM5z1SbIyqP952ljBzUJFxzZomEoh9XGmq132jIP5+uxf3XzZEzc6UymUMa1FBxQEPtCxDg3ECZjrr8lQunDyKwgTcJqknCjhYrFKLm/8uWyDcwcq2llDAMehxFfnvw4WNCc/xWaqc5gOK9pR424aGmY6cNzlrcAgg2uqdU+8s7sUMhT10v7dx767ZzwNjziIgzbV71JLpDDZNvzReTALIFfW+NgfiTaQk481+UlPf2LU25Eq6MHMRGIdmR2OaU5y8Jl8EhaTUtxlr5Z3bAtA/lDY25tju9VebfwicbV38Xgl4s21CR7QiJbUKCGAO6QskPuLDzi+fbFdxusur6K+bR3Mf1NrhoKbucRJCCfHC3/cXNwhlSYT6uxvMWDl/WRgh4LZQ0ue/lHIMWyMpwwqQ/xpICY3Px3ua+yesbsjreYmDNbDTGvmVeu9QCk7qHFOkMdYJp7aYvSjNlk/hwLwa67oaUTwKttiuXXkycHJnMJW3qkF7fstfALimK1D5qIs737U01wa+CCTGMoKbF52LVLfk9xOISNjWXabeXLn8WLpYtf1zCx32NRaIgLzs+kRYW1Y4aoe2ae4c5GO+IJcQ/kkaMEvshHWP+jMBAObpFXAODNc2f4y8G7oZiv/PVYkwaKrtZJ92WzCOJ6PWeczBKM8SRWo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
